name: issue-to-hexo

runs:
    using: 'node20'
    main: './index.js'

inputs:
    token:
        description: 'GitHub token'
        required: false
        default: ${{ github.token }}
    issue_number:
        description: 'Issue number'
        required: true
