name: Issue to Hexo
on:
  issues:
    # Sufficient to trigger this workflow when an issue is milestoned
    types: [ milestoned ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gsongsong/issue-to-hexo@v1
        with:
          issue_url: ${{ github.event.issue.url }}
          token: ${{ github.token }}
      
