name: Issue to Hexo
run-name: 'create blog for issue #${{ github.event.inputs.issueNumber }}'
on:
  workflow_dispatch:
    inputs:
      issueNumber:
        required: true
        type: number
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: init pnpm
        uses: pnpm/action-setup@v2
        with:
            version: 8

      - name: init node
        uses: actions/setup-node@v4
        with:
            node-version: 20
            cache: 'pnpm'
            cache-dependency-path: 'src'

      - name: install dependencies
        working-directory: src
        run: pnpm install
        
      - name: generate issue to hexo
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const issueNumber = "${{ github.event.inputs.issueNumber }}";
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber
            });
            console.log('==issue', issue);
            const { title, body } = issue.data;

            const path = `action-test/${title}`

            await exec.exec(
              `pnpm hexo new`,
              [
                `--path ${path}`,
                title,
              ],
              {
                cwd: 'src',
                // silent: true,
                // ignoreReturnCode: true,
              }
            );
            
            await exec.exec(
              `echo "${body}" > source/_posts/${path}.md`,
              [],
              [
                `--path action-test/${title}`,
                title,
              ],
              {
                cwd: 'src',
                // silent: true,
                // ignoreReturnCode: true,
              }
            );

            return '';

      - name: generate hexo
        run: pnpm run build

      - name: create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
            title: New blog by Action
            base: master
            branch: feat/new-blog-by-action
      
